### ISSUE TITLE
Issue labels: do we need them all?

### ISSUE THREAD

**Issue by adrianusler** [Molara-Lab/Molara#295] opened 2024-03-01 13:39 UTC
I think that it could make sense to have some labels for specific topics, e.g.
- rendering (i have already created this label)
- io (file input/output)
- calculations (e.g., molecular orbitals, force fields, ...)

On the other hand, we should then maybe make some room by removing some labels that no one ever uses. What do you think about these:
- help wanted
- invalid
- dependencies (could be part of "housekeeping"?)
- wontfix

**Comment by ab5424** [comment] 2024-03-01 14:02
invalid and wontfix are meant for issues that are denied (either because it is not an actual issue but rather an user error or because we not consider it with fixing). Help wanted is for when there is not a bug but rather a question how to use the software. All three labels are propably more directed to (external) users than core developers. I'm against removing them.

Dependencies is used by dependabot (pull requests).

**Comment by adrianusler** [comment] 2024-03-01 15:06
> invalid and wontfix are meant for issues that are denied (either because it is not an actual issue but rather an user error or because we not consider it with fixing). Help wanted is for when there is not a bug but rather a question how to use the software. All three labels are propably more directed to (external) users than core developers. I'm against removing them.
> 
> Dependencies is used by dependabot (pull requests).

Alright, thanks for your opinion. I had doubts whether we will realistically use these labels. Maybe we can change the sorting, such that the specific labels (like rendering) are on top of the list, and the more exotic ones like wontfix at the bottom?

**Comment by ab5424** [comment] 2024-03-01 15:55
Yes, that sounds good.

**Comment by adrianusler** [comment] 2024-03-01 16:47
> Yes, that sounds good.

But apparently, the sorting is alphabetical no matter what we do

**Comment by adrianusler** [comment] 2024-03-01 22:07
> So, we leave it as it is?

I guess... but I added some new labels anyway

**Closed** 2024-03-02 07:34 UTC
Labels: question
